version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "6000:6000"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

networks:
  elk_network:
    driver: bridge
